# Actividad clase 4

# Luis Edgardo Ordoñez Alvarez expdt.751856 22/08/2024

1. TOMA EL ARCHIVO DE EXCEL PROPOCIONADO PREVIAMENTE Y:
   * Calcula la Utilidad (Ingreso - Gasto)
   * Encuentra el promedio de Gastos en los meses que la Utilidad fue negativa
   * encuentra los ingresos totales del año

# Calcula la Utilidad (Ingreso - Gasto)

In [18]:
import pandas as pd

In [20]:
datos = pd.read_excel("datosCT.xlsx")
datos

Unnamed: 0  Ingreso  Gasto
0        Enero     1340   1880
1      Febrero     2590   3130
2        Marzo     3570   2140
3        Abril     4450   3370
4         Mayo     1330   2990
5        Junio     1610   1970
6        Julio     1500   2230
7       Agosto     2270   1240
8   Septiembre     1910   1470
9      Octubre     2120   2280
10   Noviembre     3950   1870
11   Diciembre     1380   3140

In [22]:
datos["Utilidad"] = datos["Ingreso"] - datos["Gasto"]
datos

Unnamed: 0  Ingreso  Gasto  Utilidad
0        Enero     1340   1880      -540
1      Febrero     2590   3130      -540
2        Marzo     3570   2140      1430
3        Abril     4450   3370      1080
4         Mayo     1330   2990     -1660
5        Junio     1610   1970      -360
6        Julio     1500   2230      -730
7       Agosto     2270   1240      1030
8   Septiembre     1910   1470       440
9      Octubre     2120   2280      -160
10   Noviembre     3950   1870      2080
11   Diciembre     1380   3140     -1760

# Encuentra el promedio de Gastos en los meses que la Utilidad fue negativa

In [28]:
datos_utilidad_negativa = datos[ datos["Utilidad"]<0 ]

In [30]:
np.mean(datos_utilidad_negativa["Gasto"])

2517.1428571428573

# Encuentra los ingresos totales del año

In [32]:
sum(datos["Ingreso"])

28020

2. CREA LAS SIGUIENTES ESTRUCTURAS USANDO NUMPY Y ENCUENTRA EL RESULTADO DE Ab->]

In [6]:
import numpy as np

In [8]:
A = np.array([
    [1, 2],
    [3, 4]
])

A

array([[1, 2],
       [3, 4]])

In [10]:
b = np.array([
    [2],
    [4]
])

b

array([[2],
       [4]])

In [12]:
# Por lo tanto

In [14]:
A @ b

array([[10],
       [22]])